=== ArmagetronAd/armagetronad/resource/proto/map-0.3.1-a.dtd
<!-- version="0.3.1-a" -->
<!ELEMENT Resource (Map)>

<!ATTLIST Resource
       type (aamap) "aamap" 
       name CDATA #REQUIRED
       version CDATA "1.0"
       author CDATA "Anonymous"
       category CDATA "unsorted"
       comissioner CDATA #IMPLIED
>

<!ELEMENT Map (Settings?, World)> 

<!ELEMENT Settings (Setting*)>
<!ELEMENT Setting EMPTY>
<!ATTLIST Setting name CDATA #REQUIRED>
<!ATTLIST Setting value CDATA #REQUIRED>

<!-- ATM, a map contain only one Field -->
<!ELEMENT World (Field)>
<!-- a field 
  - may have an axes declared
  - need at least one spawn
  - need at least one wall -->
<!ELEMENT Field (Axes?, (Spawn | Wall | Monitor | Zone )*)>

<!ELEMENT Axes (Axis*)>
<!ELEMENT Spawn EMPTY> 
<!ELEMENT Wall (Point+) >
<!ELEMENT Point EMPTY>
<!ELEMENT Axis EMPTY>
<!ELEMENT Zone (ShapeCircle, (Enter | Inside | Leave | Outside)+ ) >

<!ATTLIST Map version CDATA #REQUIRED>

<!ATTLIST Field logicalBox (true | false) "true">

<!ATTLIST Axes number CDATA "4">
<!ATTLIST Axes normalize (true | false) "true">

<!ATTLIST Spawn x CDATA #REQUIRED>
<!ATTLIST Spawn y CDATA #REQUIRED>
<!ATTLIST Spawn xdir CDATA #IMPLIED>
<!ATTLIST Spawn ydir CDATA #IMPLIED>
<!ATTLIST Spawn angle CDATA #IMPLIED>
<!ATTLIST Spawn length CDATA "1.0">

<!ATTLIST Wall height CDATA #IMPLIED>

<!ATTLIST Point x CDATA #REQUIRED>
<!ATTLIST Point y CDATA #REQUIRED>

<!ATTLIST Axis xdir CDATA #IMPLIED>
<!ATTLIST Axis ydir CDATA #IMPLIED>
<!ATTLIST Axis angle CDATA #IMPLIED>
<!ATTLIST Axis length CDATA "1.0">


<!ATTLIST Zone name CDATA "">

<!ELEMENT Monitor (OnOver | OnUnder | InRange | OutsideRange)+ >
<!ATTLIST Monitor name  CDATA #REQUIRED>
<!ATTLIST Monitor init  CDATA "0.0">
<!ATTLIST Monitor drift CDATA "0.0">
<!ATTLIST Monitor low   CDATA "0.0">
<!ATTLIST Monitor high  CDATA "1.0">

<!ELEMENT OnOver (EffectGroup+) >
<!ATTLIST OnOver value  CDATA #REQUIRED>

<!ELEMENT OnUnder (EffectGroup+) >
<!ATTLIST OnUnder value CDATA #REQUIRED>

<!ELEMENT InRange (EffectGroup+) >
<!ATTLIST InRange low   CDATA #REQUIRED>
<!ATTLIST InRange high  CDATA #REQUIRED>

<!ELEMENT OutsideRange (EffectGroup+) >
<!ATTLIST OutsideRange low  CDATA #REQUIRED>
<!ATTLIST OutsideRange high CDATA #REQUIRED>


<!ELEMENT ShapeCircle (Point, Color)>
<!ATTLIST ShapeCircle radius CDATA #REQUIRED>
<!ATTLIST ShapeCircle growth CDATA "0.0">

<!ELEMENT Color EMPTY>
<!ATTLIST Color red   CDATA "1.0">
<!ATTLIST Color green CDATA "0.0">
<!ATTLIST Color blue  CDATA "0.0">
<!ATTLIST Color alpha  CDATA "0.0">

<!ELEMENT Enter   (EffectGroup+) >
<!ELEMENT Inside  (EffectGroup+) >
<!ELEMENT Leave   (EffectGroup+) >
<!ELEMENT Outside (EffectGroup+) >

<!ELEMENT EffectGroup (User)>
<!ATTLIST EffectGroup owners CDATA #IMPLIED>
<!ATTLIST EffectGroup teamOwners CDATA #IMPLIED>

<!ELEMENT User (Target | MonitorInfluence | ZoneInfluence)+ >
<!ATTLIST User user (all | owner | ownerTeam | allButOwner | allButTeamOwner | anotherTeammate) "all" >
<!ATTLIST User positive (true | false | ignore) "ignore" >
<!ATTLIST User marked   (true | false | ignore) "ignore" >


<!ELEMENT Target (Effect)+ >
<!ATTLIST Target target (self | teammate | team | all | allButSelf |
 another | 
owner | ownerTeam | ownerTeamTeammate | anyDead |
allDead | anotherTeammateDead | anotherNotTeammateDead |
singleDeadOwner
) "self" >
<!-- 
<!ATTLIST Target target (self | teammate | team | all | allButSelf |
allButTeam | another | anotherTeam | anotherTeammate |
anotherNotTeammate | owner | ownerTeam | ownerTeamTeammate | anyDead |
allDead | AnotherTeammateDead | anotherNotTeammateDead) "self" >
-->
<!ATTLIST Target count CDATA "-1">


<!ELEMENT Effect EMPTY>
<!ATTLIST Effect effect (win | death | point | brakerecharge |
rubberrecharge | spawnplayer | setting ) "death" >
<!ATTLIST Effect count CDATA "-1">
<!ATTLIST Effect description CDATA #IMPLIED>
<!ATTLIST Effect score CDATA "1"> <!-- only for point -->
<!ATTLIST Effect settingName CDATA #IMPLIED> <!-- only for setting -->
<!ATTLIST Effect settingValue CDATA #IMPLIED><!-- only for setting -->


<!ELEMENT MonitorInfluence EMPTY>
<!ATTLIST MonitorInfluence name CDATA #IMPLIED>
<!ATTLIST MonitorInfluence marked (true | false | ignore) "ignore">
<!ATTLIST MonitorInfluence influenceSlide CDATA #IMPLIED>
<!ATTLIST MonitorInfluence influenceAdd   CDATA #IMPLIED>
<!ATTLIST MonitorInfluence influenceSet   CDATA #IMPLIED>


<!ELEMENT ZoneInfluence (Rotation | Radius | Point | Color)+ >
<!ATTLIST ZoneInfluence name CDATA #IMPLIED>

<!ELEMENT Rotation EMPTY>
<!ATTLIST Rotation rotationSpeed CDATA "0.0">
<!ATTLIST Rotation rotationAcceleration CDATA "0.0">

<!ELEMENT Radius EMPTY>
<!ATTLIST Radius radius CDATA "1.0">

=== ArmagetronAd/armagetronad/resource/proto/spinning_square.aamap.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Resource SYSTEM "map-0.3.1-a.dtd">
<Resource type="aamap" name="spinning_square" version="0.0.2" author="Anonymous" category="polygon/regular">
	<Map version="2">
		<World>
			<Field>
				<Spawn	x="255"	y="50"	xdir="0"	ydir="1"	/>
				<Spawn	x="245"	y="450"	xdir="0"	ydir="-1"	/>
				<Spawn	x="50"	y="245"	xdir="1"	ydir="0"	/>
				<Spawn	x="450"	y="255"	xdir="-1"	ydir="0"	/>

				<Spawn	x="305"	y="100"	xdir="0"	ydir="1"	/>
				<Spawn	x="195"	y="400"	xdir="0"	ydir="-1"	/>
				<Spawn	x="100"	y="195"	xdir="1"	ydir="0"	/>
				<Spawn	x="400"	y="305"	xdir="-1"	ydir="0"	/>

				<Spawn	x="205"	y="100"	xdir="0"	ydir="1"	/>
				<Spawn	x="295"	y="400"	xdir="0"	ydir="-1"	/>
				<Spawn	x="100"	y="295"	xdir="1"	ydir="0"	/>
				<Spawn	x="400"	y="205"	xdir="-1"	ydir="0"	/>
				
				<Wall height="0.01">
						<Point x="-104" y="-104" />
						<Point x="-104"  y="604" />
						<Point  x="604"  y="604" />
						<Point  x="604" y="-104" />
						<Point x="-104" y="-104" />
				</Wall>
				
				<Zone>
					<ShapePolygon rotation="0;.05">
						<!-- Origin point -->
						<Point  x="250" y="250" />
						<Color red="1" green=".7" blue=".7" />
						<!-- Shape -->
						<Point x="-250" y="-250" />
						<Point x="-250"  y="250" />
						<Point  x="250"  y="250" />
						<Point  x="250" y="-250" />
						<Point x="-250" y="-250" />
					</ShapePolygon>
					<Leave>
						<EffectGroup>
							<User>
								<Target>
									<Effect effect="death" />
								</Target>
							</User>
						</EffectGroup>
					</Leave>
				</Zone>
			</Field>
		</World>
	</Map>
</Resource>

=== ArmagetronAd/armagetronad/resource/proto/philippeqc/quadFortress.aamap.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Resource SYSTEM "map-0.3.1-a.dtd">
<!--
<Resource type="aamap" name="square" version="1.0.1" author="Anonymous" category="polygon/regular">
-->
<Resource type="aamap" version="a" name="quadFortress"  author="philippeqc" category="fortress">
 <Map version="2">
  <World>
  <Field>
   <Axes number="4" />
<!--
   <Axes number="4" >
     <Axis xdir="-1" ydir="-1"/>
     <Axis xdir="-1" ydir="1"/>
     <Axis xdir="1"  ydir="1"/>
     <Axis xdir="1"  ydir="-1"/>
   </Axes>
-->

   <Ownership>
     <TeamOwnership teamId="blue" playerId="azure,cobalt,midnight,royal"/>
     <TeamOwnership teamId="red" playerId="cerise,mauve,rust,sangria"/>
     <TeamOwnership teamId="green" playerId="emerald,jade,lime,olive"/>
     <TeamOwnership teamId="yellow" playerId="amber,goldenrod,lemon,navajowhite"/>
   </Ownership>

   <Spawn x="50"  y="50"  angle="45"/>
   <Spawn x="450" y="50"  angle="135"/>
   <Spawn x="450" y="450" angle="225"/>
   <Spawn x="50"  y="450" angle="315"/>



   <Wall>
    <Point x="0" y="0"/>
    <Point x="500" y="0"/>
    <Point x="500" y="500"/>
    <Point x="0" y="500"/>
    <Point x="0" y="0"/>
   </Wall>


   <Zone name="forAzurePlayer">
     <ShapeCircle scale="50">
       <Point x="100" y="100"/>
       <Color red="0.0" green="0.027" blue="1.0"/>
     </ShapeCircle>
     <Enter>
       <EffectGroup owners="azure,cobalt">
         <User user="owner">
	   <Target target="self">
	     <Effect effect="point" score="3" count="4"/>
	   </Target>
	 </User>
       </EffectGroup>
     </Enter>
   </Zone>

   <Zone name="forBlueTeam">
     <ShapeCircle scale="50">
       <Point x="200" y="200"/>
       <Color red="0.0" green="0.0" blue="1.0"/>
     </ShapeCircle>
     <Enter>
       <EffectGroup teamOwners="blue">
         <User user="ownerTeam">
	   <Target target="self">
	     <Effect effect="point" score="3" count="4"/>
	   </Target>
	 </User>
       </EffectGroup>
     </Enter>
   </Zone>

<!--
   <Zone name="BigSquare">
    <ShapePolygon scale="50" rotation="time()*3.14*2/5">
     <Point x="250+50*cos(time()*3.14*2/5)"
            y="250+50*sin(time()*3.14*2/5)"/>
     <Point x="250"
            y="250"/>
     <Color red="0.5" green="0.0" blue="0.0"/>
     <Point x= "0.5" y= "0.5" />
     <Point x="-0.5" y= "0.5" />
     <Point x="-0.5" y="-0.5" />
     <Point x= "0.5" y="-0.5" />
     <Point x= "0.5" y="-0.55" />
     <Point x="-0.5" y="-0.55" />
     <Point x="-0.5" y="0.55" />
     <Point x= "0.5" y="0.55" />

    </ShapePolygon>
    <Enter>
      <EffectGroup owners="">
       <User user="all">
        <Target target="self">
         <Effect effect="death"/>
        </Target>
       </User>
      </EffectGroup>
    </Enter>
   </Zone>
-->

   <!-- Experiment: A rotating zone. Totally unsynchronized when used over the network -->
<!-- 
   <Zone name="RotatingZone">
    <ShapePolygon scale="50" rotation="time()*3.14*2/5">
     <Point x="250"
            y="250"/>
     <Color red="0.5" green="0.0" blue="0.0"/>
     <Point x= "0.05" y= "0.0" />
     <Point x= "0.05" y= "0.5" />
     <Point x="-0.05" y= "0.5" />
     <Point x="-0.05" y= "0.0" />

    </ShapePolygon>
    <Enter>
      <EffectGroup owners="">
       <User user="all">
        <Target target="self">
         <Effect effect="death"/>
        </Target>
       </User>
      </EffectGroup>
    </Enter>
   </Zone>
-->

  </Field>
  </World>
 </Map>
</Resource>
